/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:81e6b4a4-0f79-4d37-b9c1-a3cedc840fd9",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_0itWoGD9f",
    "aws_user_pools_web_client_id": "4lgnqq43t0vo3gd4atj9ek4p7l",
    "oauth": {},
    "aws_user_files_s3_bucket": "next-tail-amp-bucket112805-dev",
    "aws_user_files_s3_bucket_region": "us-east-1",
    "predictions": {
        "identify": {
            "identifyText": {
                "proxy": false,
                "region": "us-east-1",
                "defaults": {
                    "format": "ALL"
                }
            }
        },
        "convert": {
            "translateText": {
                "region": "us-east-1",
                "proxy": false,
                "defaults": {
                    "sourceLanguage": "id",
                    "targetLanguage": "en"
                }
            }
        }
    }
};


export default awsmobile;
